# -*- coding: utf-8 -*-
# Generated by Django 3.2.7 on 2021-10-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="identityprovider",
            table="identity_providers",
        ),
        migrations.CreateModel(
            name="SWA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("public_key_fingerprint", models.CharField(max_length=255, null=True)),
                ("public_key", models.TextField(null=True)),
                ("claimant_url", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "idp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.identityprovider",
                    ),
                ),
            ],
            options={
                "db_table": "swas",
            },
        ),
    ]
