# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2021-10-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20211015_0730"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprovider",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="swa",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="swa",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
