# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2021-11-01 19:56

from django.db import migrations


def add_default_swas(apps, schema_editor):
    SWA = apps.get_model("api", "SWA")
    SWA.objects.get_or_create(code="NJ", name="New Jersey", status=1)
    SWA.objects.get_or_create(
        code="AR", name="Arkansas", status=1
    )  # can't use SWA.StatusOptions.ACTIVE


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_identityprovider_name"),
    ]

    operations = [
        migrations.RunPython(add_default_swas),
    ]
