# -*- coding: utf-8 -*-
# Generated by Django 3.2.9 on 2021-11-04 16:40

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api", "0006_auto_20211101_1956"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_id", models.BigIntegerField()),
                ("category", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("happened_at", models.DateTimeField(default=timezone.now)),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["model_name", "model_id"], name="events_model_n_2544b6_idx"
            ),
        ),
    ]
