# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-02-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_claim_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimant",
            name="IAL",
            field=models.IntegerField(choices=[(1, "Ial1"), (2, "Ial2")], default=1),
        ),
    ]
