# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-02-07 23:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_claimant_ial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimantFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fileext", models.CharField(max_length=4)),
                (
                    "filetype",
                    models.IntegerField(
                        choices=[(0, "Unknown"), (1, "F1099G")], default=0
                    ),
                ),
                ("year", models.CharField(max_length=4)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.claimant"
                    ),
                ),
                (
                    "swa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.swa"
                    ),
                ),
            ],
            options={
                "db_table": "claimant_files",
            },
        ),
    ]
