# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-02-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_claimantfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimant",
            name="encryption_key_hash",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="claimant",
            index=models.Index(
                fields=["encryption_key_hash"], name="claimants_encrypt_e3d57b_idx"
            ),
        ),
    ]
