# -*- coding: utf-8 -*-
# Generated by Django 3.2.12 on 2022-02-10 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("api", "0011_auto_20220207_2353")]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS django_celery_beat_periodictask;"
            "DROP TABLE IF EXISTS django_celery_beat_periodictasks;"
            "DROP TABLE IF EXISTS django_celery_beat_solarschedule;"
            "DROP TABLE IF EXISTS django_celery_beat_intervalschedule;"
            "DROP TABLE IF EXISTS django_celery_beat_crontabschedule;"
            "DROP TABLE IF EXISTS django_celery_beat_clockedschedule"
        )
    ]
