# -*- coding: utf-8 -*-
# Generated by Django 3.2.12 on 2022-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_arkansas_identity_featureset"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["updated_at"], name="claims_updated_00c59e_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["category"], name="events_categor_a7129c_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["happened_at"], name="events_happene_b402e3_idx"
            ),
        ),
    ]
