# -*- coding: utf-8 -*-
# Generated by Django 3.2.12 on 2022-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20220308_2056"),
    ]

    operations = [
        migrations.AddField(
            model_name="swa",
            name="fullname",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
